spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TestCase
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  lifetime: 30m
server:
  port: 8080
  servlet:
    context-path: /testCase
flyway:
  user: postgres
  password: postgres
  schemas: public
  url: jdbc:postgresql://localhost:5432/TestCase
  locations: filesystem:db/migration